apiVersion: v1
kind: Service
metadata:
  name: codelabs
spec:
  type: NodePort
  selector:
    app: codelabs
  ports:
    - port: 80
      targetPort: 30007
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelabs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codelabs
  template:
    metadata:
      labels:
        app: codelabs
    spec:
      containers:
        - name: codelabs
          image: fanickarthis/webapp:0.0.1
          ports:
            - containerPort: 30007
