apiVersion: v1
kind: Service
metadata:
  name: codelabs
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: codelabs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelabs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codelabs
  template:
    metadata:
      labels:
        app: codelabs
    spec:
      containers:
      - name: codelabs
        image: fanickarthis/webapp:tagname
        ports:
        - containerPort: 8080
