apiVersion: v1
kind: Service
metadata:
  name: codelabs
spec:
  selector:
    app: codelabs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.97.130.151
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.0.20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelabs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codelabs
  template:
    metadata:
      labels:
        app: codelabs
    spec:
      containers:
        - name: codelabs
          image: fanickarthis/webapp:0.0.1
          ports:
            - containerPort: 80
