apiVersion: v1
kind: Service
metadata:
  name: codelabs-service
spec:
  selector:
    app: codelabs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.97.130.151
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.0.20
