apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelabs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codelabs
  template:
    metadata:
      labels:
        app: codelabs
    spec:
      containers:
        - name: codelabs
          image: fanickarthis/webapp:0.0.1
          ports:
            - containerPort: 80
